trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo k8s pipeline!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=${client_id} -var client_secret=${client_secret} -var ssh_public_key=${publickey.secureFilePath}'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmTenantId: 'a44edf86-8712-42e0-a9c2-7821b0ad95de'
    backendAzureRmSubscriptionId: '6284f523-9ae0-46dd-b5b7-b5e35c00d431"'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'st14586885ghcv'
    backendAzureRmContainerName: 'st14586885container'
    backendAzureRmKey: 'k8s-dev.tfstate'
    allowTelemetryCollection: true
  


